<?php

// Create dummy appointments
function create_dummy_appointments( $count, $days ) {
    // DB table
    global $wpdb;
    $table_name = $wpdb->prefix.'tc_appointments';

    // get array of all staff user
    $allstaffs = get_users( ['role' => 'staff'] );
    $allstaffs = json_decode( json_encode( $allstaffs ), true );
    foreach ( $allstaffs as $staff => $value ) {
        $staffArray[] = [
            'id'   => $value['data']['ID'],
            'name' => $value['data']['display_name']
        ];
    }
    // print_r($staffArray);

    // get array of all customer user
    $allcustomer = get_users( ['role' => 'customer'] );
    $allcustomer = json_decode( json_encode( $allcustomer ), true );
    foreach ( $allcustomer as $customer => $value ) {
        $customerArray[] = [
            'id'   => $value['data']['ID'],
            'name' => $value['data']['display_name']

        ];
    }
    // print_r($customerArray);

    // get random datetime, staff & customer and insert into db
    for ( $i = 0; $i < $count; $i++ ) {

        // random numbers
        if ( rand( 0, 1 ) ) {
            $random_date = date( 'Y-m-d', strtotime( '+'.mt_rand( 0, $days ).' days' ) );
        } else {
            $random_date = date( 'Y-m-d', strtotime( '-'.mt_rand( 0, $days ).' days' ) );
        }
        $random_hour     = str_pad( rand( 8, 18 ), 2, 0, STR_PAD_LEFT );
        $random_minute   = str_pad( rand( 0, 59 ), 2, 0, STR_PAD_LEFT );
        $durations       = [30, 60, 90, 120, 150, 180];
        $random_duration = $durations[mt_rand( 0, 5 )];
        // startdate
        $random_datetime_start = $random_date.' '.$random_hour.':'.$random_minute.':00';
        // enddate is startdate + duration
        $datetime = new DateTime( $random_datetime_start );
        $datetime->add( new DateInterval( 'PT'.$random_duration.'M' ) );
        $random_datetime_end = $datetime->format( 'Y-m-d H:i:s' );
        // echo $random_datetime_start;
        // echo "<br>";
        // echo $random_datetime_end;

        $allstaff_length = count( $allstaffs ) - 1;
        $random_staff    = $staffArray[rand( 0, $allstaff_length )];
        // print_r($random_staff);

        $allcustomer_length = count( $allcustomer ) - 1;
        $random_customer    = $customerArray[rand( 0, $allcustomer_length )];
        // print_r($random_customer);

        $allprojects = get_pages( ['post_type' => 'project', 'authors' => $random_customer['id']] );

        // echo $random_customer['id']."<br>";
        // print_r($allprojects);

        $allprojects_length = count( $allprojects ) - 1;
        $random_project     = $allprojects[rand( 0, $allprojects_length )];

        // print_r($random_project->ID);
        // exit;
        $array = [
            'create_date' => current_time( 'mysql' ),
            'staff_id'    => $random_staff['id'],
            'customer_id' => $random_customer['id'],
            'project_id'  => $random_project->ID,
            'date_start'  => $random_datetime_start,
            'date_end'    => $random_datetime_end,
            'duration'    => $random_duration,
            'meta'        => 'just a free field for any information'
        ];

        // create post, post_type_appointment
        $my_post = [
            'post_title'   => $random_datetime_start,
            'post_content' => 'details for appointment',
            'post_type'    => 'appointment',
            'post_status'  => 'publish',
            'post_author'  => $random_staff['id']
        ];
        $post_id = wp_insert_post( $my_post );

        // add data to custom table
        $array['post_id'] = $post_id;
        $insert           = $wpdb->insert( $table_name, $array );

        // print_r($array);
    }
    // exit;
}

// CREATE DUMMY USER
function create_dummy_customer( $count ) {
    // add_action('init', function () use ($count) {
    for ( $i = 0; $i < $count; $i++ ) {
        $random_name = random_name();

        $params = [
            'name'       => $random_name[0]." ".$random_name[1],
            'first_name' => $random_name[0],
            'last_name'  => $random_name[1],
            'email'      => $random_name[0]."@".$random_name[1].".com",
            'meta'       => "",
            'vac'        => "",
            'color'      => "color",
            'size'       => "size"
        ];
        // print_r($params);
        add_new_customer( $params );
    }
    // });
}

// // CREATE DUMMY USER
// function create_dummy_staff( $count ) {
//     // add_action('init', function () use ($count) {
//     for ( $i = 0; $i < $count; $i++ ) {
//         $random_name = random_name();
//         $username    = $random_name[0]." ".$random_name[1];
//         $email       = $random_name[0]."@".$random_name[1].".com";

//         $user_id = username_exists( $username );

//         if ( !$user_id && email_exists( $email ) == false ) {
//             $userdata = [
//                 'user_pass'     => 'password',
//                 'user_login'    => $username,
//                 'user_nicename' => $random_name[0]."_".$random_name[1],
//                 'user_email'    => $email,
//                 'display_name'  => $random_name[0]." ".$random_name[1],
//                 'nickname'      => $random_name[0]." ".$random_name[1],
//                 'first_name'    => $random_name[0],
//                 'last_name'     => $random_name[1],
//                 'description'   => 'Im staff.'
//             ];

//             $user_id = wp_insert_user( $userdata );
//             $user    = get_user_by( 'id', $user_id );
//             $user->set_role( 'staff' );
//         }
//         ;
//     }
//     // });
// }

function random_text() {
    $words = random_int( 13, 18 );
    $lorem = ['lorem', 'ipsum', 'dolor', 'sit', 'amet', 'consectetur', 'adipiscing', 'elit', 'praesent', 'interdum', 'dictum', 'mi', 'non', 'egestas', 'nulla', 'in', 'lacus', 'sed', 'sapien', 'placerat', 'malesuada', 'at', 'erat', 'etiam', 'id', 'velit', 'finibus', 'viverra', 'maecenas', 'mattis', 'volutpat', 'justo', 'vitae', 'vestibulum', 'metus', 'lobortis', 'mauris', 'luctus', 'leo', 'feugiat', 'nibh', 'tincidunt', 'a', 'integer', 'facilisis', 'lacinia', 'ligula', 'ac', 'suspendisse', 'eleifend', 'nunc', 'nec', 'pulvinar', 'quisque', 'ut', 'semper', 'auctor', 'tortor', 'mollis', 'est', 'tempor', 'scelerisque', 'venenatis', 'quis', 'ultrices', 'tellus', 'nisi', 'phasellus', 'aliquam', 'molestie', 'purus', 'convallis', 'cursus', 'ex', 'massa', 'fusce', 'felis', 'fringilla', 'faucibus', 'varius', 'ante', 'primis', 'orci', 'et', 'posuere', 'cubilia', 'curae', 'proin', 'ultricies', 'hendrerit', 'ornare', 'augue', 'pharetra', 'dapibus', 'nullam', 'sollicitudin', 'euismod', 'eget', 'pretium', 'vulputate', 'urna', 'arcu', 'porttitor', 'quam', 'condimentum', 'consequat', 'tempus', 'hac', 'habitasse', 'platea', 'dictumst', 'sagittis', 'gravida', 'eu', 'commodo', 'dui', 'lectus', 'vivamus', 'libero', 'vel', 'maximus', 'pellentesque', 'efficitur', 'class', 'aptent', 'taciti', 'sociosqu', 'ad', 'litora', 'torquent', 'per', 'conubia', 'nostra', 'inceptos', 'himenaeos', 'fermentum', 'turpis', 'donec', 'magna', 'porta', 'enim', 'curabitur', 'odio', 'rhoncus', 'blandit', 'potenti', 'sodales', 'accumsan', 'congue', 'neque', 'duis', 'bibendum', 'laoreet', 'elementum', 'suscipit', 'diam', 'vehicula', 'eros', 'nam', 'imperdiet', 'sem', 'ullamcorper', 'dignissim', 'risus', 'aliquet', 'habitant', 'morbi', 'tristique', 'senectus', 'netus', 'fames', 'nisl', 'iaculis', 'cras', 'aenean'];

    $text = '';
    for ( $s = 0; $s < $words; ++$s ) {
        $i = random_int( 0, 175 );
        $text .= $lorem[$i].' ';
    }
    return $text;
}

function random_name() {
    $names = [
        'Allison',
        'Arthur',
        'Ana',
        'Alex',
        'Arlene',
        'Alberto',
        'Barry',
        'Bertha',
        'Bill',
        'Bonnie',
        'Bret',
        'Beryl',
        'Chantal',
        'Cristobal',
        'Claudette',
        'Charley',
        'Cindy',
        'Chris',
        'Dean',
        'Dolly',
        'Danny',
        'Danielle',
        'Dennis',
        'Debby',
        'Erin',
        'Edouard',
        'Erika',
        'Earl',
        'Emily',
        'Ernesto',
        'Felix',
        'Fay',
        'Fabian',
        'Frances',
        'Franklin',
        'Florence',
        'Gabielle',
        'Gustav',
        'Grace',
        'Gaston',
        'Gert',
        'Gordon',
        'Humberto',
        'Hanna',
        'Henri',
        'Hermine',
        'Harvey',
        'Helene',
        'Iris',
        'Isidore',
        'Isabel',
        'Ivan',
        'Irene',
        'Isaac',
        'Jerry',
        'Josephine',
        'Juan',
        'Jeanne',
        'Jose',
        'Joyce',
        'Karen',
        'Kyle',
        'Kate',
        'Karl',
        'Katrina',
        'Kirk',
        'Lorenzo',
        'Lili',
        'Larry',
        'Lisa',
        'Lee',
        'Leslie',
        'Michelle',
        'Marco',
        'Mindy',
        'Maria',
        'Michael',
        'Noel',
        'Nana',
        'Nicholas',
        'Nicole',
        'Nate',
        'Nadine',
        'Olga',
        'Omar',
        'Odette',
        'Otto',
        'Ophelia',
        'Oscar',
        'Pablo',
        'Paloma',
        'Peter',
        'Paula',
        'Philippe',
        'Patty',
        'Rebekah',
        'Rene',
        'Rose',
        'Richard',
        'Rita',
        'Rafael',
        'Sebastien',
        'Sally',
        'Sam',
        'Shary',
        'Stan',
        'Sandy',
        'Tanya',
        'Teddy',
        'Teresa',
        'Tomas',
        'Tammy',
        'Tony',
        'Van',
        'Vicky',
        'Victor',
        'Virginie',
        'Vince',
        'Valerie',
        'Wendy',
        'Wilfred',
        'Wanda',
        'Walter',
        'Wilma',
        'William',
        'Kumiko',
        'Aki',
        'Miharu',
        'Chiaki',
        'Michiyo',
        'Itoe',
        'Nanaho',
        'Reina',
        'Emi',
        'Yumi',
        'Ayumi',
        'Kaori',
        'Sayuri',
        'Rie',
        'Miyuki',
        'Hitomi',
        'Naoko',
        'Miwa',
        'Etsuko',
        'Akane',
        'Kazuko',
        'Miyako',
        'Youko',
        'Sachiko',
        'Mieko',
        'Toshie',
        'Junko'];

    $surnames = [
        'Abbott',
        'Acevedo',
        'Acosta',
        'Adams',
        'Adkins',
        'Aguilar',
        'Aguirre',
        'Albert',
        'Alexander',
        'Alford',
        'Allen',
        'Allison',
        'Alston',
        'Alvarado',
        'Alvarez',
        'Anderson',
        'Andrews',
        'Anthony',
        'Armstrong',
        'Arnold',
        'Ashley',
        'Atkins',
        'Atkinson',
        'Austin',
        'Avery',
        'Avila',
        'Ayala',
        'Ayers',
        'Bailey',
        'Baird',
        'Baker',
        'Baldwin',
        'Ball',
        'Ballard',
        'Banks',
        'Barber',
        'Barker',
        'Barlow',
        'Barnes',
        'Barnett',
        'Barr',
        'Barrera',
        'Barrett',
        'Barron',
        'Barry',
        'Bartlett',
        'Barton',
        'Bass',
        'Bates',
        'Battle',
        'Bauer',
        'Baxter',
        'Beach',
        'Bean',
        'Beard',
        'Beasley',
        'Beck',
        'Becker',
        'Bell',
        'Bender',
        'Benjamin',
        'Bennett',
        'Benson',
        'Bentley',
        'Benton',
        'Berg',
        'Berger',
        'Bernard',
        'Berry',
        'Best',
        'Bird',
        'Bishop',
        'Black',
        'Blackburn',
        'Blackwell',
        'Blair',
        'Blake',
        'Blanchard',
        'Blankenship',
        'Blevins',
        'Bolton',
        'Bond',
        'Bonner',
        'Booker',
        'Boone',
        'Booth',
        'Bowen',
        'Bowers',
        'Bowman',
        'Boyd',
        'Boyer',
        'Boyle',
        'Bradford',
        'Bradley',
        'Bradshaw',
        'Brady',
        'Branch',
        'Bray',
        'Brennan',
        'Brewer',
        'Bridges',
        'Briggs',
        'Bright',
        'Britt',
        'Brock',
        'Brooks',
        'Brown',
        'Browning',
        'Bruce',
        'Bryan',
        'Bryant',
        'Buchanan',
        'Buck',
        'Buckley',
        'Buckner',
        'Bullock',
        'Burch',
        'Burgess',
        'Burke',
        'Burks',
        'Burnett',
        'Burns',
        'Burris',
        'Burt',
        'Burton',
        'Bush',
        'Butler',
        'Byers',
        'Byrd',
        'Cabrera',
        'Cain',
        'Calderon',
        'Caldwell',
        'Calhoun',
        'Callahan',
        'Camacho',
        'Cameron',
        'Campbell',
        'Campos',
        'Cannon',
        'Cantrell',
        'Cantu',
        'Cardenas',
        'Carey',
        'Carlson',
        'Carney',
        'Carpenter',
        'Carr',
        'Carrillo',
        'Carroll',
        'Carson',
        'Carter',
        'Carver',
        'Case',
        'Casey',
        'Cash',
        'Castaneda',
        'Castillo',
        'Castro',
        'Cervantes',
        'Chambers',
        'Chan',
        'Chandler',
        'Chaney',
        'Chang',
        'Chapman',
        'Charles',
        'Chase',
        'Chavez',
        'Chen',
        'Cherry',
        'Christensen',
        'Christian',
        'Church',
        'Clark',
        'Clarke',
        'Clay',
        'Clayton',
        'Clements',
        'Clemons',
        'Cleveland',
        'Cline',
        'Cobb',
        'Cochran',
        'Coffey',
        'Cohen',
        'Cole',
        'Coleman',
        'Collier',
        'Collins',
        'Colon',
        'Combs',
        'Compton',
        'Conley',
        'Conner',
        'Conrad',
        'Contreras',
        'Conway',
        'Cook',
        'Cooke',
        'Cooley',
        'Cooper',
        'Copeland',
        'Cortez',
        'Cote',
        'Cotton',
        'Cox',
        'Craft',
        'Craig',
        'Crane',
        'Crawford',
        'Crosby',
        'Cross',
        'Cruz',
        'Cummings',
        'Cunningham',
        'Curry',
        'Curtis',
        'Dale',
        'Dalton',
        'Daniel',
        'Daniels',
        'Daugherty',
        'Davenport',
        'David',
        'Davidson',
        'Davis',
        'Dawson',
        'Day',
        'Dean',
        'Decker',
        'Dejesus',
        'Delacruz',
        'Delaney',
        'Deleon',
        'Delgado',
        'Dennis',
        'Diaz',
        'Dickerson',
        'Dickson',
        'Dillard',
        'Dillon',
        'Dixon',
        'Dodson',
        'Dominguez',
        'Donaldson',
        'Donovan',
        'Dorsey',
        'Dotson',
        'Douglas',
        'Downs',
        'Doyle',
        'Drake',
        'Dudley',
        'Duffy',
        'Duke',
        'Duncan',
        'Dunlap',
        'Dunn',
        'Duran',
        'Durham',
        'Dyer',
        'Eaton',
        'Edwards',
        'Elliott',
        'Ellis',
        'Ellison',
        'Emerson',
        'England',
        'English',
        'Erickson',
        'Espinoza',
        'Estes',
        'Estrada',
        'Evans',
        'Everett',
        'Ewing',
        'Farley',
        'Farmer',
        'Farrell',
        'Faulkner',
        'Ferguson',
        'Fernandez',
        'Ferrell',
        'Fields',
        'Figueroa',
        'Finch',
        'Finley',
        'Fischer',
        'Fisher',
        'Fitzgerald',
        'Fitzpatrick',
        'Fleming',
        'Fletcher',
        'Flores',
        'Flowers',
        'Floyd',
        'Flynn',
        'Foley',
        'Forbes',
        'Ford',
        'Foreman',
        'Foster',
        'Fowler',
        'Fox',
        'Francis',
        'Franco',
        'Frank',
        'Franklin',
        'Franks',
        'Frazier',
        'Frederick',
        'Freeman',
        'French',
        'Frost',
        'Fry',
        'Frye',
        'Fuentes',
        'Fuller',
        'Fulton',
        'Gaines',
        'Gallagher',
        'Gallegos',
        'Galloway',
        'Gamble',
        'Garcia',
        'Gardner',
        'Garner',
        'Garrett',
        'Garrison',
        'Garza',
        'Gates',
        'Gay',
        'Gentry',
        'George',
        'Gibbs',
        'Gibson',
        'Gilbert',
        'Giles',
        'Gill',
        'Gillespie',
        'Gilliam',
        'Gilmore',
        'Glass',
        'Glenn',
        'Glover',
        'Goff',
        'Golden',
        'Gomez',
        'Gonzales',
        'Gonzalez',
        'Good',
        'Goodman',
        'Goodwin',
        'Gordon',
        'Gould',
        'Graham',
        'Grant',
        'Graves',
        'Gray',
        'Green',
        'Greene',
        'Greer',
        'Gregory',
        'Griffin',
        'Griffith',
        'Grimes',
        'Gross',
        'Guerra',
        'Guerrero',
        'Guthrie',
        'Gutierrez',
        'Guy',
        'Guzman',
        'Hahn',
        'Hale',
        'Haley',
        'Hall',
        'Hamilton',
        'Hammond',
        'Hampton',
        'Hancock',
        'Haney',
        'Hansen',
        'Hanson',
        'Hardin',
        'Harding',
        'Hardy',
        'Harmon',
        'Harper',
        'Harrell',
        'Harrington',
        'Harris',
        'Harrison',
        'Hart',
        'Hartman',
        'Harvey',
        'Hatfield',
        'Hawkins',
        'Hayden',
        'Hayes',
        'Haynes',
        'Hays',
        'Head',
        'Heath',
        'Hebert',
        'Henderson',
        'Hendricks',
        'Hendrix',
        'Henry',
        'Hensley',
        'Henson',
        'Herman',
        'Hernandez',
        'Herrera',
        'Herring',
        'Hess',
        'Hester',
        'Hewitt',
        'Hickman',
        'Hicks',
        'Higgins',
        'Hill',
        'Hines',
        'Hinton',
        'Hobbs',
        'Hodge',
        'Hodges',
        'Hoffman',
        'Hogan',
        'Holcomb',
        'Holden',
        'Holder',
        'Holland',
        'Holloway',
        'Holman',
        'Holmes',
        'Holt',
        'Hood',
        'Hooper',
        'Hoover',
        'Hopkins',
        'Hopper',
        'Horn',
        'Horne',
        'Horton',
        'House',
        'Houston',
        'Howard',
        'Howe',
        'Howell',
        'Hubbard',
        'Huber',
        'Hudson',
        'Huff',
        'Huffman',
        'Hughes',
        'Hull',
        'Humphrey',
        'Hunt',
        'Hunter',
        'Hurley',
        'Hurst',
        'Hutchinson',
        'Hyde',
        'Ingram',
        'Irwin',
        'Jackson',
        'Jacobs',
        'Jacobson',
        'James',
        'Jarvis',
        'Jefferson',
        'Jenkins',
        'Jennings',
        'Jensen',
        'Jimenez',
        'Johns',
        'Johnson',
        'Johnston',
        'Jones',
        'Jordan',
        'Joseph',
        'Joyce',
        'Joyner',
        'Juarez',
        'Justice',
        'Kane',
        'Kaufman',
        'Keith',
        'Keller',
        'Kelley',
        'Kelly',
        'Kemp',
        'Kennedy',
        'Kent',
        'Kerr',
        'Key',
        'Kidd',
        'Kim',
        'King',
        'Kinney',
        'Kirby',
        'Kirk',
        'Kirkland',
        'Klein',
        'Kline',
        'Knapp',
        'Knight',
        'Knowles',
        'Knox',
        'Koch',
        'Kramer',
        'Lamb',
        'Lambert',
        'Lancaster',
        'Landry',
        'Lane',
        'Lang',
        'Langley',
        'Lara',
        'Larsen',
        'Larson',
        'Lawrence',
        'Lawson',
        'Le',
        'Leach',
        'Leblanc',
        'Lee',
        'Leon',
        'Leonard',
        'Lester',
        'Levine',
        'Levy',
        'Lewis',
        'Lindsay',
        'Lindsey',
        'Little',
        'Livingston',
        'Lloyd',
        'Logan',
        'Long',
        'Lopez',
        'Lott',
        'Love',
        'Lowe',
        'Lowery',
        'Lucas',
        'Luna',
        'Lynch',
        'Lynn',
        'Lyons',
        'Macdonald',
        'Macias',
        'Mack',
        'Madden',
        'Maddox',
        'Maldonado',
        'Malone',
        'Mann',
        'Manning',
        'Marks',
        'Marquez',
        'Marsh',
        'Marshall',
        'Martin',
        'Martinez',
        'Mason',
        'Massey',
        'Mathews',
        'Mathis',
        'Matthews',
        'Maxwell',
        'May',
        'Mayer',
        'Maynard',
        'Mayo',
        'Mays',
        'Mcbride',
        'Mccall',
        'Mccarthy',
        'Mccarty',
        'Mcclain',
        'Mcclure',
        'Mcconnell',
        'Mccormick',
        'Mccoy',
        'Mccray',
        'Mccullough',
        'Mcdaniel',
        'Mcdonald',
        'Mcdowell',
        'Mcfadden',
        'Mcfarland',
        'Mcgee',
        'Mcgowan',
        'Mcguire',
        'Mcintosh',
        'Mcintyre',
        'Mckay',
        'Mckee',
        'Mckenzie',
        'Mckinney',
        'Mcknight',
        'Mclaughlin',
        'Mclean',
        'Mcleod',
        'Mcmahon',
        'Mcmillan',
        'Mcneil',
        'Mcpherson',
        'Meadows',
        'Medina',
        'Mejia',
        'Melendez',
        'Melton',
        'Mendez',
        'Mendoza',
        'Mercado',
        'Mercer',
        'Merrill',
        'Merritt',
        'Meyer',
        'Meyers',
        'Michael',
        'Middleton',
        'Miles',
        'Miller',
        'Mills',
        'Miranda',
        'Mitchell',
        'Molina',
        'Monroe',
        'Montgomery',
        'Montoya',
        'Moody',
        'Moon',
        'Mooney',
        'Moore',
        'Morales',
        'Moran',
        'Moreno',
        'Morgan',
        'Morin',
        'Morris',
        'Morrison',
        'Morrow',
        'Morse',
        'Morton',
        'Moses',
        'Mosley',
        'Moss',
        'Mueller',
        'Mullen',
        'Mullins',
        'Munoz',
        'Murphy',
        'Murray',
        'Myers',
        'Nash',
        'Navarro',
        'Neal',
        'Nelson',
        'Newman',
        'Newton',
        'Nguyen',
        'Nichols',
        'Nicholson',
        'Nielsen',
        'Nieves',
        'Nixon',
        'Noble',
        'Noel',
        'Nolan',
        'Norman',
        'Norris',
        'Norton',
        'Nunez',
        'Obrien',
        'Ochoa',
        'Oconnor',
        'Odom',
        'Odonnell',
        'Oliver',
        'Olsen',
        'Olson',
        'Oneal',
        'Oneil',
        'Oneill',
        'Orr',
        'Ortega',
        'Ortiz',
        'Osborn',
        'Osborne',
        'Owen',
        'Owens',
        'Pace',
        'Pacheco',
        'Padilla',
        'Page',
        'Palmer',
        'Park',
        'Parker',
        'Parks',
        'Parrish',
        'Parsons',
        'Pate',
        'Patel',
        'Patrick',
        'Patterson',
        'Patton',
        'Paul',
        'Payne',
        'Pearson',
        'Peck',
        'Pena',
        'Pennington',
        'Perez',
        'Perkins',
        'Perry',
        'Peters',
        'Petersen',
        'Peterson',
        'Petty',
        'Phelps',
        'Phillips',
        'Pickett',
        'Pierce',
        'Pittman',
        'Pitts',
        'Pollard',
        'Poole',
        'Pope',
        'Porter',
        'Potter',
        'Potts',
        'Powell',
        'Powers',
        'Pratt',
        'Preston',
        'Price',
        'Prince',
        'Pruitt',
        'Puckett',
        'Pugh',
        'Quinn',
        'Ramirez',
        'Ramos',
        'Ramsey',
        'Randall',
        'Randolph',
        'Rasmussen',
        'Ratliff',
        'Ray',
        'Raymond',
        'Reed',
        'Reese',
        'Reeves',
        'Reid',
        'Reilly',
        'Reyes',
        'Reynolds',
        'Rhodes',
        'Rice',
        'Rich',
        'Richard',
        'Richards',
        'Richardson',
        'Richmond',
        'Riddle',
        'Riggs',
        'Riley',
        'Rios',
        'Rivas',
        'Rivera',
        'Rivers',
        'Roach',
        'Robbins',
        'Roberson',
        'Roberts',
        'Robertson',
        'Robinson',
        'Robles',
        'Rocha',
        'Rodgers',
        'Rodriguez',
        'Rodriquez',
        'Rogers',
        'Rojas',
        'Rollins',
        'Roman',
        'Romero',
        'Rosa',
        'Rosales',
        'Rosario',
        'Rose',
        'Ross',
        'Roth',
        'Rowe',
        'Rowland',
        'Roy',
        'Ruiz',
        'Rush',
        'Russell',
        'Russo',
        'Rutledge',
        'Ryan',
        'Salas',
        'Salazar',
        'Salinas',
        'Sampson',
        'Sanchez',
        'Sanders',
        'Sandoval',
        'Sanford',
        'Santana',
        'Santiago',
        'Santos',
        'Sargent',
        'Saunders',
        'Savage',
        'Sawyer',
        'Schmidt',
        'Schneider',
        'Schroeder',
        'Schultz',
        'Schwartz',
        'Scott',
        'Sears',
        'Sellers',
        'Serrano',
        'Sexton',
        'Shaffer',
        'Shannon',
        'Sharp',
        'Sharpe',
        'Shaw',
        'Shelton',
        'Shepard',
        'Shepherd',
        'Sheppard',
        'Sherman',
        'Shields',
        'Short',
        'Silva',
        'Simmons',
        'Simon',
        'Simpson',
        'Sims',
        'Singleton',
        'Skinner',
        'Slater',
        'Sloan',
        'Small',
        'Smith',
        'Snider',
        'Snow',
        'Snyder',
        'Solis',
        'Solomon',
        'Sosa',
        'Soto',
        'Sparks',
        'Spears',
        'Spence',
        'Spencer',
        'Stafford',
        'Stanley',
        'Stanton',
        'Stark',
        'Steele',
        'Stein',
        'Stephens',
        'Stephenson',
        'Stevens',
        'Stevenson',
        'Stewart',
        'Stokes',
        'Stone',
        'Stout',
        'Strickland',
        'Strong',
        'Stuart',
        'Suarez',
        'Sullivan',
        'Summers',
        'Sutton',
        'Swanson',
        'Sweeney',
        'Sweet',
        'Sykes',
        'Talley',
        'Tanner',
        'Tate',
        'Taylor',
        'Terrell',
        'Terry',
        'Thomas',
        'Thompson',
        'Thornton',
        'Tillman',
        'Todd',
        'Torres',
        'Townsend',
        'Tran',
        'Travis',
        'Trevino',
        'Trujillo',
        'Tucker',
        'Turner',
        'Tyler',
        'Tyson',
        'Underwood',
        'Valdez',
        'Valencia',
        'Valentine',
        'Valenzuela',
        'Vance',
        'Vang',
        'Vargas',
        'Vasquez',
        'Vaughan',
        'Vaughn',
        'Vazquez',
        'Vega',
        'Velasquez',
        'Velazquez',
        'Velez',
        'Villarreal',
        'Vincent',
        'Vinson',
        'Wade',
        'Wagner',
        'Walker',
        'Wall',
        'Wallace',
        'Waller',
        'Walls',
        'Walsh',
        'Walter',
        'Walters',
        'Walton',
        'Ward',
        'Ware',
        'Warner',
        'Warren',
        'Washington',
        'Waters',
        'Watkins',
        'Watson',
        'Watts',
        'Weaver',
        'Webb',
        'Weber',
        'Webster',
        'Weeks',
        'Weiss',
        'Welch',
        'Wells',
        'West',
        'Wheeler',
        'Whitaker',
        'White',
        'Whitehead',
        'Whitfield',
        'Whitley',
        'Whitney',
        'Wiggins',
        'Wilcox',
        'Wilder',
        'Wiley',
        'Wilkerson',
        'Wilkins',
        'Wilkinson',
        'William',
        'Williams',
        'Williamson',
        'Willis',
        'Wilson',
        'Winters',
        'Wise',
        'Witt',
        'Wolf',
        'Wolfe',
        'Wong',
        'Wood',
        'Woodard',
        'Woods',
        'Woodward',
        'Wooten',
        'Workman',
        'Wright',
        'Wyatt',
        'Wynn',
        'Yang',
        'Yates',
        'York',
        'Young',
        'Zamora',
        'Zimmerman'];

    //Generate a random forename.
    $random_name = $names[mt_rand( 0, sizeof( $names ) - 1 )];

    //Generate a random surname.
    $random_surname = $surnames[mt_rand( 0, sizeof( $surnames ) - 1 )];

    //Combine them together and print out the result.
    // echo $random_name . ' ' . $random_surname;
    return [$random_name, $random_surname];
}