export default {
    'de': {
        // common
        'S_title': 'S-M-D',
        'edit': 'Bearbeiten',
        'new': 'Neu',
        'save': 'Speichern',
        'delete': 'Löschen',
        'search': 'Suche',
        // dropdown
        'select-Staff': 'Mitarbeiter auswählen',
        'select-Customer': 'Kunden auswählen',
        // headlines
        'staff_fields': 'Mitarbeiter Tabelle',
        'customer_fields': 'Kunden Tabelle',
        'Staff-Profile': 'Mitarbeiter Profil',
        "Customer-Profile": 'Kunden Profil',
        // Sidebar
        'S_menu': 'Menü',
        'S_staff': 'Mitarbeiter',
        'S_staff-profile': 'Mitarbeiterprofil',
        'S_profile-form': 'Profil Elemente',
        'S_customer': 'Kunden',
        'S_customer-profile': 'Kundenprofil',
        'S_solarsystem': 'Sonnensystem',
        'S_form': 'Formulare',
        'S_form1': 'Formular I',
        'S_form2': 'Formular II',
        'S_dummy': 'Platzhalter',
        // profil elemente
        'P_edit_entry': 'Eintäge editieren',
        'P_new_entry': 'Neuer Eintrag',
        // form labels
        'F_id': 'ID',
        'F_username': 'Anmeldename',
        'F_email': 'Email',
        'F_password': 'Passwort',
        'F_firstname': 'Vorname',
        'F_lastname': 'Nachname',
        'F_comment': 'Kommentar',
        'F_role': 'Rolle',
        'F_permission': 'Berechtigungen',
        'F_date': 'Datum',
        'F_street': 'Straße',
        'F_street_nr': 'Nr.',
        'F_city': 'Stadt',
        'F_city_nr': 'PLZ',
        'F_phone': 'Telefon',

    },
    'en': {
        // common
        'S_title': 'S-M-D',
        'edit': 'Edit',
        'new': 'New',
        'save': 'Save',
        'delete': 'Delete',
        'search': 'Search',
        // dropdown
        'select-Staff': 'Select Staff',
        'select-Customer': 'Select Customer',
        // headlines
        'staff_fields': 'Staff Table',
        'customer_fields': 'Customer Table',
        'Staff-Profile': 'Staff Profile',
        "Customer-Profile": 'Customer Profile',
        //sidebar
        'S_menu': 'Menu',
        'S_staff': 'Staff',
        'S_staff-profile': 'Staffprofile',
        'S_profile-form': 'Profile Elements',
        'S_customer': 'Customer',
        'S_customer-profile': 'Customerprofile',
        'S_solarsystem': 'Solarsystem',
        'S_form': 'Forms',
        'S_form1': 'Form I',
        'S_form2': 'Form II',
        'S_dummy': 'Dummy',
        // profil elemente
        'P_edit_entry': 'Edit Entry',
        'P_new_entry': 'New Entry',
        // form labels
        'F_id': 'ID',
        'F_username': 'Username',
        'F_email': 'Email',
        'F_password': 'Password',
        'F_firstname': 'Firstame',
        'F_lastname': 'Lastname',
        'F_comment': 'Comment',
        'F_role': 'Role',
        'F_permission': 'Permission',
        'F_date': 'Date',
        'F_street': 'Street',
        'F_street_nr': 'No.',
        'F_city': 'City',
        'F_city_nr': 'Postcode',
        'F_phone': 'Phone',

    }
}